name: mac 12
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Mac
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Setting Up Mac
      env:
        
        MAC_USER_PASSWORD: ${{ secrets.MAC_USER_PASSWORD }}
       
        
      run: source macos.sh "$MAC_USER_PASSWORD"
   

    
    - name: System running...
      run: sleep 21550
      
